// Icons
export const newPostIcon = require("../assets/icons/newPost.png");
export const plusIcon = require("../assets/icons/plus.png");
import heart from '../assets/icons/Heart.svg';
export const HeartIcon = heart;
import redHeart from "../assets/icons/RedHeart.svg";
export const RedHeartIcon = redHeart;
import search from "../assets/icons/Search.svg";
export const SearchIcon = search; 
import bookmark from "../assets/icons/Bookmark.svg";
export const BookmarkIcon = bookmark;
import union from "../assets/icons/Union.svg";
export const UnionIcon = union; 
import house from "../assets/icons/House.svg";
export const HouseIcon = house;
import logo from "../assets/icons/Logo.svg";
export const LogoIcon = logo;
import comment from "../assets/icons/Comment.svg";
export const CommentIcon = comment;
import points from "../assets/icons/Points.svg";
export const PointsIcon = points; 
import share from "../assets/icons/Share.svg";
export const ShareIcon = share;
import message from "../assets/icons/Message.svg";
export const MessageIcon = message;
import stroke from "../assets/icons/Stroke.svg";
export const StrokeIcon = stroke;